config/routes.rb
Rails.application.routes.draw do


  # resources :subscribers
  get "privacy", to: 'static_pages#privacy_policy', as: "privacy"
  get "terms", to: 'static_pages#terms_of_use', as: "terms"

  get '/login', to: 'session#new', as: 'login'
  post '/login', to: 'session#create'
  delete '/logout', to: 'session#destroy', as: 'logout'


  # resources :authors


  post '/subscribe', to: 'subscribe#create'
  resources :account_activations, only: [:edit] # sets up just the edit action for this route



  # resources :subscribers, only: %i[new create update edit destroy]

  # get 'errors/not_found'
  # get 'errors/unacceptable'
  # get 'errors/internal_error'
  # get 'not_found/unacceptable'
  # get 'not_found/internal_error'
  # localhost:3000/

  root 'welcome#index'

  resources :authors, only: :show

  # localhost:3000/dashboard/
  scope :dashboard do
    # only viewable to admin
    get '/', to: 'dashboard#index', as: 'dashboard'
    get '/tags', to: 'dashboard#tags', as: 'dashboard_tags'
    resources :posts, param: :slug, except: :show
    delete :delete_attachment, to: 'attachment_control#delete_attachment', as: 'delete_attachment'
    resources :categories, param: :slug, except: :show
    resources :inquiries, only: %i[index new create destroy]
    resources :subscribers


    resources :authors, except: :show

    # resources :subscribers, only: %i[index edit destroy]
    # get '/subscribers', to: 'subscribers#index'
      end

  ### Resetting resources here

  # localhost:3000/article/2018/09/12/some-title
  # scope :article do
    # /article/some-time-of-an-article
    # get '/article/:year/:month/:day/:slug', to: 'display#post', as: 'display_post'
    get '/article/:slug', to: 'display#post', as: 'display_post'
    get '/category/:slug', to: 'display#category', as: 'display_category'
    get '/tag/:tag_name', to: 'display#tags', as: 'tag'
  # end

  # scope :search do
    # get '/', to: "display#search"
    # get '/date/:year', to: 'display#date'
    # get '/date/:year/:month', to: 'display#date'
    # get '/date/:year/:month/:day', to: 'display#date'
  # end

  # 404s not found pages, but allows for rails blobs
  match '*unmatched', to: 'application#route_not_found', via: :all, constraints: lambda { |request| !request.url.include?('rails') }

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_action :author_must_be_signed_in_to_access

  def index
    @newest_posts = Post.where(active: true).order(created_at: :desc).first(25)

    @inactive_posts = Post.where(active: false)

    # @unanswered_comments

    @categories = Category.all

    # @tags =
  end


  def tags
    @tags = ActsAsTaggableOn::Tag.all
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_dashboard_sidebar.html.erb
<aside class="dashboard-menu">
  <ul>

    <li><%= link_to 'Home', dashboard_path %></li>
    <li class="menu-title">Post</li>
    <li><%= link_to 'Create New', new_post_path, data: { turbolinks: false } %></li>
    <li><%= link_to 'List All', posts_path %></li>

    <li class="menu-title">Categories</li>
    <li><%= link_to 'Create New', new_category_path %></li>
    <li><%= link_to 'List All', categories_path %></li>

    <li class="menu-title">Subscribers</li>
    <li><%= link_to 'List All', subscribers_path %></li>

    <li class="menu-title">Authors</li>
    <li><%= link_to 'Create New', new_author_path %></li>
    <li><%= link_to 'List All', authors_path %></li>

    <li class="menu-title">Tags</li>
    <li><%= link_to 'List All', dashboard_tags_path %></li>

    <li class="menu-title">Contact Us</li>
    <li><%= link_to 'List Messages', inquiries_path %></li>

    <li class="menu-title">APIs</li>
    <li><a href="https://app.sendgrid.com/login" target="_blank" rel="noreferrer">SendGrid</a></li>
    <li><a href="#">AWS</a></li>

  </ul>
</aside>

app/views/dashboard/index.html.erb
<h1>Dashboard</h1>

<h1>Save this page for analytics</h1>

<!-- ~~~~~~~~~~ NEWEST ACTIVE POSTS ~~~~~~~~~~ -->

<h2>Newest Active Posts</h2>
<table>
  <thead>
    <tr>
      <th>Created</th>
      <th>Activated</th>
      <th>Updated</th>
      <th>Title</th>
      <th>Page Views</th>
      <th>Comments</th>
      <th>Replies</th>
      <th>Category</th>
      <th>Tags</th>
      <th><!-- Leave Blank --></th>
    </tr>
  </thead>
<tbody>
<% @newest_posts.each do |post| %>
<tr>
  <td><%= post.created_at.strftime("%B %d, %Y") %></td>
  <td><%= post.activation_date.strftime("%B %d, %Y") %></td>
  <td><%= post.updated_at.strftime("%B %d, %Y") %></td>
  <td><%= link_to post.title, completed_display_post_path(post), target: '_blank' %></td>
  <td><%= post.page_count %></td>
  <td><%= post.category.name %></td>
  <td></td>
  <td><%= link_to 'Edit', edit_post_path(post), data: { turbolinks: false } %></td>
</tr>
<% end %>
</tbody>
</table>

<!-- ~~~~~~~~~~ NEWEST INACTIVE POSTS ~~~~~~~~~~ -->

<h2>Inactive Posts</h2>

<table>
  <thead>
    <tr>
      <th>Created</th>
      <th>Updated</th>
      <th>Will Activate</th>
      <th>Title</th>
      <th>Category</th>
      <th>Tags</th>
      <th><!-- EDIT: Leave Blank --></th>
    </tr>
  </thead>
<tbody>
<% @inactive_posts.each do |post| %>
<tr>
  <td><%= post.created_at.strftime("%B %d, %Y") %></td>
  <td><%= post.updated_at.strftime("%B %d, %Y") %></td>
  <% if post.activation_date == nil %>
    <td>Activation Date Not Set</td>
  <% else %>
    <td><%= post.activation_date.strftime("%B %d, %Y") %></td>
  <% end %>
  <td><%= link_to post.title, post %></td>
  <td><%= post.category.name %></td>
  <td></td>
  <td><%= link_to 'Edit', edit_post_path(post), data: { turbolinks: false } %></td>
</tr>
<% end %>
</tbody>
</table>

app/views/dashboard/tags.html.erb
<h1>Tags</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Taggings Count</th>
      <th></th>
    </tr>
  </thead>

  <tbody>


<% @tags.each do |tag| %>
<tr>
  <td><%= tag.name %></td>
  <td><%= tag.taggings_count %></td>
  <td><%= link_to 'View', tag_path(tag.name), target: '_blank' %></td>
</tr>

<% end %>
  </tbody>
</table>