config/routes.rb
Rails.application.routes.draw do


  # resources :subscribers
  get "privacy", to: 'static_pages#privacy_policy', as: "privacy"
  get "terms", to: 'static_pages#terms_of_use', as: "terms"

  get '/login', to: 'session#new', as: 'login'
  post '/login', to: 'session#create'
  delete '/logout', to: 'session#destroy', as: 'logout'


  # resources :authors


  post '/subscribe', to: 'subscribe#create'
  resources :account_activations, only: [:edit] # sets up just the edit action for this route



  # resources :subscribers, only: %i[new create update edit destroy]

  # get 'errors/not_found'
  # get 'errors/unacceptable'
  # get 'errors/internal_error'
  # get 'not_found/unacceptable'
  # get 'not_found/internal_error'
  # localhost:3000/

  root 'welcome#index'

  resources :authors, only: :show

  # localhost:3000/dashboard/
  scope :dashboard do
    # only viewable to admin
    get '/', to: 'dashboard#index', as: 'dashboard'
    get '/tags', to: 'dashboard#tags', as: 'dashboard_tags'
    resources :posts, param: :slug, except: :show
    delete :delete_attachment, to: 'attachment_control#delete_attachment', as: 'delete_attachment'
    resources :categories, param: :slug, except: :show
    resources :inquiries, only: %i[index new create destroy]
    resources :subscribers


    resources :authors, except: :show

    # resources :subscribers, only: %i[index edit destroy]
    # get '/subscribers', to: 'subscribers#index'
      end

  ### Resetting resources here

  # localhost:3000/article/2018/09/12/some-title
  # scope :article do
    # /article/some-time-of-an-article
    # get '/article/:year/:month/:day/:slug', to: 'display#post', as: 'display_post'
    get '/article/:slug', to: 'display#post', as: 'display_post'
    get '/category/:slug', to: 'display#category', as: 'display_category'
    get '/tag/:tag_name', to: 'display#tags', as: 'tag'
  # end

  # scope :search do
    # get '/', to: "display#search"
    # get '/date/:year', to: 'display#date'
    # get '/date/:year/:month', to: 'display#date'
    # get '/date/:year/:month/:day', to: 'display#date'
  # end

  # 404s not found pages, but allows for rails blobs
  match '*unmatched', to: 'application#route_not_found', via: :all, constraints: lambda { |request| !request.url.include?('rails') }

end

app/models/author.rb
class Author < ApplicationRecord
  has_secure_password

  has_many :posts

  has_one_attached :profile_image
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :author_must_be_signed_in_to_access, except: [:show]
  before_action :set_author, only: [:show, :edit, :update, :destroy]


  # GET /authors
  def index
    @authors = Author.all
  end

  # GET /authors/1
  def show
    @posts = Post.where(author_id: @author.id).order(created_at: :desc).paginate(:page => params[:page], :per_page => 15)
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  def create
    @author = Author.new(author_params)

    if @author.save
      redirect_to @author, notice: 'Author was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /authors/1
  def update
    if @author.update(author_params)
      redirect_to @author, notice: 'Author was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /authors/1
  def destroy
    @author.destroy
    redirect_to authors_url, notice: 'Author was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def author_params
      params.require(:author).permit(:name, :email_address, :bio, :password, :password_confirmation, :authorization_token, :authorized, :profile_image)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true, html: { class: 'dashboard_form' }) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
  <%= form.label :profile_image %>
  <%= form.file_field :profile_image %>
</div>

<% if author.profile_image.attached? %>
  <%= image_tag rails_blob_url(author.profile_image), style: 'height: 100px; width: auto;' %>
  <%= link_to 'Delete Main Image', delete_attachment_url(id: author.profile_image.id),
                              method: :delete,
                              confirm: { data: 'Are you sure?' },
                              style: 'display: block;' %>
<% end %>

  <div class="field">
    <%= form.label :email_address %>
    <%= form.text_field :email_address %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email address</th>
      <th>Bio</th>
      <th>Password digest</th>
      <th>Authorization token</th>
      <th>Authorized</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.email_address %></td>
        <td><%= author.bio %></td>
        <td><%= author.password_digest %></td>
        <td><%= author.authorization_token %></td>
        <td><%= author.authorized %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<h2 class="tags-title"><%= @author.name %></h2>

<%= render 'shared/card_list_layout', iteration: @posts  %>

<%= will_paginate @posts, inner_window: 3, outer_window: 3 %>