config/routes.rb
Rails.application.routes.draw do


  # resources :subscribers
  get "privacy", to: 'static_pages#privacy_policy', as: "privacy"
  get "terms", to: 'static_pages#terms_of_use', as: "terms"

  get '/login', to: 'session#new', as: 'login'
  post '/login', to: 'session#create'
  delete '/logout', to: 'session#destroy', as: 'logout'


  # resources :authors


  post '/subscribe', to: 'subscribe#create'
  resources :account_activations, only: [:edit] # sets up just the edit action for this route



  # resources :subscribers, only: %i[new create update edit destroy]

  # get 'errors/not_found'
  # get 'errors/unacceptable'
  # get 'errors/internal_error'
  # get 'not_found/unacceptable'
  # get 'not_found/internal_error'
  # localhost:3000/

  root 'welcome#index'

  resources :authors, only: :show

  # localhost:3000/dashboard/
  scope :dashboard do
    # only viewable to admin
    get '/', to: 'dashboard#index', as: 'dashboard'
    get '/tags', to: 'dashboard#tags', as: 'dashboard_tags'
    resources :posts, param: :slug, except: :show
    delete :delete_attachment, to: 'attachment_control#delete_attachment', as: 'delete_attachment'
    resources :categories, param: :slug, except: :show
    resources :inquiries, only: %i[index new create destroy]
    resources :subscribers


    resources :authors, except: :show

    # resources :subscribers, only: %i[index edit destroy]
    # get '/subscribers', to: 'subscribers#index'
      end

  ### Resetting resources here

  # localhost:3000/article/2018/09/12/some-title
  # scope :article do
    # /article/some-time-of-an-article
    # get '/article/:year/:month/:day/:slug', to: 'display#post', as: 'display_post'
    get '/article/:slug', to: 'display#post', as: 'display_post'
    get '/category/:slug', to: 'display#category', as: 'display_category'
    get '/tag/:tag_name', to: 'display#tags', as: 'tag'
  # end

  # scope :search do
    # get '/', to: "display#search"
    # get '/date/:year', to: 'display#date'
    # get '/date/:year/:month', to: 'display#date'
    # get '/date/:year/:month/:day', to: 'display#date'
  # end

  # 404s not found pages, but allows for rails blobs
  match '*unmatched', to: 'application#route_not_found', via: :all, constraints: lambda { |request| !request.url.include?('rails') }

end

app/views/shared/_card_list_layout.html.erb
<section id="card-container">

<div id="card-wrapper">

<% iteration.each do |post| %>

<%= render 'shared/single_card', post: post, coltype: 'three-col' %>

<% end %>

</div>
</section>

app/views/shared/_single_card.html.erb
<div class="article-card <%= coltype %>">


<div class="article-card-border">
<%= link_to completed_display_post_path(post), class:'image-wrapper' do %>
<div class="card-image" style="background-image: url(<%= rails_representation_url post.main_image.variant(resize: "832x590") %>)">

</div>
<% end %>


<div class="card-tag-wrapper">

  <% post.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag.name) %>
  <% end %>

</div>


<div class="article-card-content">


<h4 class="card-title"><%= link_to post.title.titleize ,completed_display_post_path(post) %></h4>
<h5 class="card-category"><%= link_to post.category.name, display_category_path(post.category) %></h5>

<hr/>


<p class="card-summary"><%= post.summary %></p>





<div class="button-wrapper">
<%= link_to 'READ MORE' ,completed_display_post_path(post), class: 'read-more-button' %>
</div>

</div>


<div class="card-bottom-info">
  <p><%= post.created_at.strftime("%B %d, %Y") %></p>

  <p><%= link_to post.author.name, author_path(post.author) %></p>
</div>


</div>
    </div>

app/views/shared/_subscribe_form.html.erb
<%= form_for Subscriber.new do |f| %>
  <%= f.text_field 'email', placeholder: 'myemail@domain.com' %>
  <%= f.submit 'subscribe' %>
<% end %>

<%#= form_for 'sub', url: subscribe_path do |f| %>
  <%#= f.text_field 'email_address', placeholder: 'myemail@domain.com' %>
  <%#= f.submit 'subscribe' %>
<%# end %>

app/views/shared/_title_border.html.erb
<div class="border-wrapper">
  <div class="side-border"></div>
  <div class="middle-border">&#x25C9;</div>
  <div class="side-border"></div>
</div>

app/views/shared/_two_column_card_layout.html.erb
<!-- Posts -->
<section id="card-container">

<div id="card-wrapper">

<% iteration = Post.first(2) %>

<% iteration.each do |post| %>

<%= link_to completed_display_post_path(post), class: 'article-link card two-col', data: {created_at: post.created_at.strftime('%Y%m%d'), category: post.category.name, title: post.title, view_count: post.page_count} do %>

<article>

  <div class="card-image-wrapper">
  <div class="card-image" style="background-image: url(<%= rails_representation_url post.main_image.variant(resize: "832x590") %>)">
  </div>
  </div>

  <div class="card-contents">
    <h4 class="card-title"><%= post.title.titleize %></h4>
    <p><%= post.summary %></p>
  </div>

</article>


<h6 class="card-tag impact"><%= post.category.name %></h6>
<% end %>


<% end %>

</div>
</section>