config/routes.rb
Rails.application.routes.draw do


  # resources :subscribers
  get "privacy", to: 'static_pages#privacy_policy', as: "privacy"
  get "terms", to: 'static_pages#terms_of_use', as: "terms"

  get '/login', to: 'session#new', as: 'login'
  post '/login', to: 'session#create'
  delete '/logout', to: 'session#destroy', as: 'logout'


  # resources :authors


  post '/subscribe', to: 'subscribe#create'
  resources :account_activations, only: [:edit] # sets up just the edit action for this route



  # resources :subscribers, only: %i[new create update edit destroy]

  # get 'errors/not_found'
  # get 'errors/unacceptable'
  # get 'errors/internal_error'
  # get 'not_found/unacceptable'
  # get 'not_found/internal_error'
  # localhost:3000/

  root 'welcome#index'

  resources :authors, only: :show

  # localhost:3000/dashboard/
  scope :dashboard do
    # only viewable to admin
    get '/', to: 'dashboard#index', as: 'dashboard'
    get '/tags', to: 'dashboard#tags', as: 'dashboard_tags'
    resources :posts, param: :slug, except: :show
    delete :delete_attachment, to: 'attachment_control#delete_attachment', as: 'delete_attachment'
    resources :categories, param: :slug, except: :show
    resources :inquiries, only: %i[index new create destroy]
    resources :subscribers


    resources :authors, except: :show

    # resources :subscribers, only: %i[index edit destroy]
    # get '/subscribers', to: 'subscribers#index'
      end

  ### Resetting resources here

  # localhost:3000/article/2018/09/12/some-title
  # scope :article do
    # /article/some-time-of-an-article
    # get '/article/:year/:month/:day/:slug', to: 'display#post', as: 'display_post'
    get '/article/:slug', to: 'display#post', as: 'display_post'
    get '/category/:slug', to: 'display#category', as: 'display_category'
    get '/tag/:tag_name', to: 'display#tags', as: 'tag'
  # end

  # scope :search do
    # get '/', to: "display#search"
    # get '/date/:year', to: 'display#date'
    # get '/date/:year/:month', to: 'display#date'
    # get '/date/:year/:month/:day', to: 'display#date'
  # end

  # 404s not found pages, but allows for rails blobs
  match '*unmatched', to: 'application#route_not_found', via: :all, constraints: lambda { |request| !request.url.include?('rails') }

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @posts = Post.first(24)
    @featured_posts = Post.last(5)
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper


  def display_subscription_message(index)

    messages =
    [
      "Subscribe For Future Updates",
      "Get Gold Delivered To Your Inbox",
      "Subscriptions for the Modern World",
      "Subscribe, Just Do it!"
    ]

    return messages[index % messages.size]

  end


end

app/views/welcome/_bottom_sidebar.html.erb
<div class="col-4">

  <div class="subscribe-sidebar">
    <div class="inner-subscribe-sidebar">

      <h4><%= subscription_message %></h4>
      <%= render 'shared/subscribe_form' %>
      <h6 class="terms-disclaimer">By clicking subscribe you are agreeing to our <%= link_to 'terms', terms_path %></h6>

    </div>
  </div>

</div>

app/views/welcome/_single_welcome_card.html.erb
<div class="col-4">

  <%= link_to completed_display_post_path(post), class: 'link-for-image-wrapper' do %>
    <div class="welcome-main-featured-image" style="background-image: url(<%= rails_representation_url post.main_image.variant(resize: "720x720") %>)">
      <h4><%= post.title %></h4>
    </div>
  <% end %>
</div>

app/views/welcome/_small_post_image_layout.html.erb
<div class="row">
  <% iteration.each do |post| %>
    <div class="col-6">
      <div class="column-text-card">
        <%= link_to completed_display_post_path(post) do %>
        <div class="small-post-image" style="background-image: url(<%= rails_representation_url post.main_image.variant(resize: " 300x300") %>"></div>
      <% end %>
      <h4><%= link_to post.title, completed_display_post_path(post) %></h4>
      <p><%= post.summary %></p>
    </div>
  </div>
<% end %>
</div>

app/views/welcome/_top_sidebar.html.erb
<div class="col-4">
  <div class="popular-posts">
    <ul>
      <% category.posts.last(5).each do |post| %>
        <li><%= link_to post.title, completed_display_post_path(post) %></li>
        <li class="post-view-count">900 views</li>
      <% end %>
        <li><%= link_to 'View More', display_category_path(category), class: 'view-more-link' %></li>
    </ul>
  </div>
</div>

app/views/welcome/_welcome_card_layout_1.html.erb
<h2 class="welcome-title welcome-title-right">
  <%= link_to category.name, display_category_path(category) %>
</h2>



<div class="row">

  <div class="col-4">

    <div class="image-height-wrapper">
      <% Post.last(2).each do |post| %>
        <%= link_to display_post_path(post) do %>
          <div class="image-half-height" style="background-image: url(<%= rails_representation_url post.main_image.variant(resize: "720x720") %>)">
            <h4><%= post.title %></h4>
          </div>
        <% end %>
      <% end %>
    </div>

  </div>

  <div class="col-4">

    <div class="image-height-wrapper">
      <% Post.first(10).last(2).each do |post| %>
        <%= link_to display_post_path(post) do %>
          <div class="image-half-height" style="background-image: url(<%= rails_representation_url post.main_image.variant(resize: "720x720") %>)">
            <h4><%= post.title %></h4>
          </div>
        <% end %>
      <% end %>
    </div>

  </div>

  <div class="col-4 welcome-initial-sidebar">

    <div class="popular-posts">

      <ul>
        <% Post.last(5).each do |post| %>
          <li><%= link_to post.title, display_post_path(post) %></li>
          <li>900 views</li>
        <% end %>
          <li><%= link_to 'View More', display_category_path(category), class: 'view-more-link' %></li>
      </ul>

    </div>

    <div class="subscribe-sidebar">
      <div class="inner-subscribe-sidebar">

        <h4><%= subscription_message %></h4>
        <%= render 'shared/subscribe_form' %>
        <h6 class="terms-disclaimer">By clicking subscribe you are agreeing to our <%= link_to 'terms', terms_path %></h6>

      </div>
    </div>

  </div>

</div>

<%= render 'shared/text_only_card_list_layout', iteration: Post.last(4) %>

app/views/welcome/_welcome_card_main_layout.html.erb
<%= render 'welcome_title', category: category, side: side %>

<!-- First Row -->
<div class="row" id="top-welcome-row-for-height">

  <% if side == "left" %>
    <%= render 'top_sidebar', category: category, subscription_message: subscription_message %>
  <% end %>

  <!-- left col featured images -->
  <%= render 'single_welcome_card', post: category.posts.last %>  <!-- category.posts.last -->

  <!-- right col featured images -->
  <%= render 'single_welcome_card', post: category.posts.first %>

  <% if side == "right" %>
    <%= render 'top_sidebar', category: category, subscription_message: subscription_message %>
  <% end %>

</div>




<!-- Second Row -->
<div class="row welcome-card-row">

  <% if side == "left" %>
    <%= render 'bottom_sidebar', category: category, subscription_message: subscription_message %>
  <% end %>

  <%= render 'single_welcome_card', post: category.posts.last(3).first %>

  <%= render 'single_welcome_card', post: category.posts.first(3).last %>

  <% if side == "right" %>
    <%= render 'bottom_sidebar', category: category, subscription_message: subscription_message %>
  <% end %>

</div>

<%= render 'small_post_image_layout', iteration: category.posts.last(6).first(4) %>

app/views/welcome/_welcome_title.html.erb
<div class="row">
  <% if side == 'left' %>
    <div class="col-4">
      <h2 class="welcome-title">
        <%= link_to category.name, display_category_path(category) %>
      </h2>
    </div>
  <% end %>

  <div class="col-8">
    <div class="empty-welcome-space"></div>
  </div>

  <% if side == 'right' %>
    <div class="col-4">
      <h2 class="welcome-title">
        <%= link_to category.name, display_category_path(category) %>
      </h2>
    </div>
  <% end %>
</div>

app/views/welcome/index.html.erb
<div class="welcome-main-image-wrapper" style="background-image: url(<%= asset_url 'sample_hero.jpg' %>)">
  <h1>Welcome to a whole new you.</h1>
</div>


<% Category.main_categories.each_with_index do |category, index| %>

  <%# Category.where(parent_id: category.id).each do |sub_category| %>

    <%# if sub_category.posts.any? %>
    <% if category.category_has_posts? %>

      <% if index % 2 == 0 %>
        <%= render 'welcome_card_main_layout', category: category, side: 'left', subscription_message: display_subscription_message(index) %>
      <% else %>
        <%= render 'welcome_card_main_layout', category: category, side: 'right', subscription_message: display_subscription_message(index) %>
      <% end %>

    <% end %>

  <% end %>

<%# end %>